p013AspNetMVCEgitim/Controllers/MVC08ViewResultsController.cs
using Microsoft.AspNetCore.Mvc;
using p013AspNetMVCEgitim.Models;

namespace p013AspNetMVCEgitim.Controllers
{
    public class MVC08ViewResultsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Yonlendir(string arananDeger)
        {
            //return Redirect("/Home"); // bu action tetiklendiğinde uygulama anasayfaya gitsin.
            //return Redirect($"/Home?kelime={arananDeger}"); // burada ? işaretinden sonraki kısım querystring yöntemi ile adres çubuğu üzerinden veri yollamak için 
            return Redirect("https://getbootstrap.com");
        }
        public IActionResult ActionaYonlendir()
        {
            //return RedirectToAction("Index"); // metot çalıştığında aynı controllerdaki bir actiona yönlendirmemizi
            return RedirectToAction("Index", "Home"); // metot çalıştığında farklı bir controller daki actiona bu şekilde yönlendirebiliriz
        }
        public RedirectToRouteResult RouteYonlendir() //IActionResult da yapsaydık kabul ederdi.
        {
            return RedirectToRoute("Default", new { controller = "Home", action = "Index", id = 18 }); // metot çalıştığında route sistemiyle yönlendirme yapmamızı sağlar
        }
        public PartialViewResult KategorileriGetirPartial() // IActionResult da yapsaydık kabul ederdi.
        {
            return PartialView("_KategorilerPartial");
        }
        public IActionResult XmlContentResult()
        {
            var xml = @"
                <Kullanicilar>
                <Kullanici>
                    <Adi>
                      Mete
                    </Adi>
                    <Soyadi>
                       Başkafa
                    </Soyadi>
                </Kullanici>
                    <Kullanici>
                    <Adi>
                      Alp
                    </Adi>
                    <Soyadi>
                       Arslan
                    </Soyadi>
                </Kullanici>
                </Kullanicilar>
            ";
            return Content(xml, "application/xml"); // geriye xml içeriğini döndürdük
        }
        public IActionResult JsonDondur()
        {

            var kullanici = new Kullanici()
            {
                Ad = "Alp",
                Soyad = "Çakmak",
                KullaniciAdi = "alpi"
            };
            return Json(kullanici);
        }
    }
}

p013AspNetMVCEgitim/Views/MVC08ViewResults/Index.cshtml
@{
}
<h1>MVC View Results Çeşitleri</h1>
<h4>
    Redirect Result : Sayfayı bir url adresine yönlendirmeyi sağlar
</h4>
@Html.ActionLink("Redirect Result","Yonlendir")
<a href="/MVC08ViewResults/Yonlendir?arananDeger=aspNetMvc">Query String</a>
<hr />

<h4>
    Redirect to Action Result : Sayfayı bir actiona yönlendirmemizi sağlar
</h4>
<a asp-action="ActionaYonlendir"> Redirect to Action</a>
<hr />
<h4>
    Redirect to Route Result : Sayfayı  bir route a yönlendirmemizi sağlar
</h4>
<a asp-action="RouteYonlendir"> Redirect to Route</a>
<hr />
<h4>
    PartialView Result :Actiona gelecek istek sonucunda geriye partial view döndürmeyi sağlar
</h4>
<a asp-action="KategorileriGetirPartial"> PartialView Result</a>

<partial name="_KategorilerPartial" />

<input type="button" value="Kategorileri Getir" class="btn btn-warning" id="btnKategorileriGetirPartial" />
<br />
<div id="Kategoriler">
</div>
@section scripts{
    <script>
        function KategorileriGetir() {
            $.ajax({ // jquery nin ajax metoduyla uygulamaya istek göndereceğiz
                url: "@Url.Action("KategorileriGetirPartial","MVC08ViewResults")", // uygulamada istek göndereceğimiz adres
                type: "GET", // ajax isteğimizin türü
                dataType: "html", // verilerinm kullanılacağı tip html formatında
                success: function (data) { // istek başarılı olursa
                    $("#Kategoriler").html(data) // id si kategoriler olan dive istek sonucu gelen ve data değişkeninde tutulan veriyi yaz 
                },
                Error: function(){
                    alert("Hata Oluştu!")
                }
            });
        }
        $(function(){
            $("#btnKategorileriGetirPartial").click(function(){ // id si btnKategorileriGetirPartial olan butona tıkladığında 
            KategorileriGetir() // üstteki metodu çalıştır
            })
        })
    </script>
}
<h4>
    XmlContent Result : Actiona gelecek istek sonucunda geriye XmlContent döndürmeyi sağlar
</h4>
<a asp-action="XmlContentResult">XmlContent Result </a>

<hr />

<h4>
    Json Result : Actiona gelecek istek sonucunda geriye Json döndürmeyi sağlar
</h4>
<a asp-action="JsonDondur">Json Result </a>